export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const EDIT_PATIENT = 'EDIT_PATIENT';
export const FETCH_TEMPLATE = 'FETCH_TEMPLATE';
export const REVIEW_PATIENT = 'REVIEW_PATIENT';
export const SUBMIT_PATIENT = 'SUBMIT_PATIENT';
export const SUBMITTED_PATIENT = 'SUBMITTED_PATIENT';
